export enum ObjectViewerType {
    button = "button",
    chart = "chart",
    dailymotion = "dailymotion",
    file = "file",
    googledocs = "googledocs",
    googlesheets = "googlesheets",
    googleslides = "googleslides",
    iframe = "iframe",
    image = "image",
    list = "list",
    object = "object",
    pdf = "pdf",
    rating = "rating",
    slideshare = "slideshare",
    table = "table",
    text = "text",
    vimeo = "vimeo",
    youtube = "youtube",
}
